"""initial gameplay schema

Revision ID: aa735a0061dc
Revises:
Create Date: 2026-10-03 18:49:51.122555

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa735a0061dc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_profiles",
        sa.Column("uid", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("nickname", sa.String(length=32), nullable=True),
        sa.Column("friend_code", sa.String(length=8), nullable=False),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(op.f("ix_player_profiles_friend_code"), "player_profiles", ["friend_code"], unique=True)
    op.create_table(
        "friend_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pair_low", sa.String(length=128), nullable=False),
        sa.Column("pair_high", sa.String(length=128), nullable=False),
        sa.Column("requester_uid", sa.String(length=128), nullable=False),
        sa.Column("recipient_uid", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pair_high"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pair_low"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pair_low", "pair_high", name="uq_friend_request_pair"),
    )
    op.create_index(op.f("ix_friend_requests_pair_high"), "friend_requests", ["pair_high"], unique=False)
    op.create_index(op.f("ix_friend_requests_pair_low"), "friend_requests", ["pair_low"], unique=False)
    op.create_index(op.f("ix_friend_requests_status"), "friend_requests", ["status"], unique=False)
    op.create_table(
        "friendships",
        sa.Column("player_low_uid", sa.String(length=128), nullable=False),
        sa.Column("player_high_uid", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["player_high_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_low_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("player_low_uid", "player_high_uid"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("current_turn_uid", sa.String(length=128), nullable=True),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("winner_uid", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["current_turn_uid"], ["player_profiles.uid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["winner_uid"], ["player_profiles.uid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_status"), "matches", ["status"], unique=False)
    op.create_table(
        "active_match_players",
        sa.Column("player_uid", sa.String(length=128), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("player_uid"),
    )
    op.create_index(
        op.f("ix_active_match_players_match_id"), "active_match_players", ["match_id"], unique=False
    )
    op.create_table(
        "battle_challenges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sender_uid", sa.String(length=128), nullable=False),
        sa.Column("recipient_uid", sa.String(length=128), nullable=False),
        sa.Column("pair_low", sa.String(length=128), nullable=False),
        sa.Column("pair_high", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pair_high"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pair_low"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pair_low", "pair_high", name="uq_challenge_pair"),
    )
    op.create_index(
        op.f("ix_battle_challenges_recipient_uid"), "battle_challenges", ["recipient_uid"], unique=False
    )
    op.create_index(
        op.f("ix_battle_challenges_sender_uid"), "battle_challenges", ["sender_uid"], unique=False
    )
    op.create_index(op.f("ix_battle_challenges_status"), "battle_challenges", ["status"], unique=False)
    op.create_table(
        "match_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("player_uid", sa.String(length=128), nullable=False),
        sa.Column("client_action_id", sa.String(length=36), nullable=False),
        sa.Column("action_type", sa.String(length=24), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("resulting_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_uid", "client_action_id", name="uq_match_action_idempotency"),
    )
    op.create_index(op.f("ix_match_actions_match_id"), "match_actions", ["match_id"], unique=False)
    op.create_table(
        "match_participants",
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("player_uid", sa.String(length=128), nullable=False),
        sa.Column("seat", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_uid"], ["player_profiles.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("match_id", "player_uid"),
        sa.UniqueConstraint("match_id", "seat", name="uq_match_participant_seat"),
    )
    op.create_table(
        "matchmaking_pairs",
        sa.Column("pair_id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pair_id"),
        sa.UniqueConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matchmaking_pairs")
    op.drop_table("match_participants")
    op.drop_index(op.f("ix_match_actions_match_id"), table_name="match_actions")
    op.drop_table("match_actions")
    op.drop_index(op.f("ix_battle_challenges_status"), table_name="battle_challenges")
    op.drop_index(op.f("ix_battle_challenges_sender_uid"), table_name="battle_challenges")
    op.drop_index(op.f("ix_battle_challenges_recipient_uid"), table_name="battle_challenges")
    op.drop_table("battle_challenges")
    op.drop_index(op.f("ix_active_match_players_match_id"), table_name="active_match_players")
    op.drop_table("active_match_players")
    op.drop_index(op.f("ix_matches_status"), table_name="matches")
    op.drop_table("matches")
    op.drop_table("friendships")
    op.drop_index(op.f("ix_friend_requests_status"), table_name="friend_requests")
    op.drop_index(op.f("ix_friend_requests_pair_low"), table_name="friend_requests")
    op.drop_index(op.f("ix_friend_requests_pair_high"), table_name="friend_requests")
    op.drop_table("friend_requests")
    op.drop_index(op.f("ix_player_profiles_friend_code"), table_name="player_profiles")
    op.drop_table("player_profiles")
    # ### end Alembic commands ###
